/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedTipsRouteImport } from './routes/_authenticated/tips'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedForecastRouteImport } from './routes/_authenticated/forecast'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedOperatorUsersRouteImport } from './routes/_authenticated/operator.users'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as AuthenticatedOperatorUsersUserIdRouteImport } from './routes/_authenticated/operator.users.$userId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTipsRoute = AuthenticatedTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForecastRoute = AuthenticatedForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorUsersRoute =
  AuthenticatedOperatorUsersRouteImport.update({
    id: '/operator/users',
    path: '/operator/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOperatorUsersUserIdRoute =
  AuthenticatedOperatorUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedOperatorUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tips': typeof AuthenticatedTipsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/operator/users': typeof AuthenticatedOperatorUsersRouteWithChildren
  '/operator/users/$userId': typeof AuthenticatedOperatorUsersUserIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tips': typeof AuthenticatedTipsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/operator/users': typeof AuthenticatedOperatorUsersRouteWithChildren
  '/operator/users/$userId': typeof AuthenticatedOperatorUsersUserIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/forecast': typeof AuthenticatedForecastRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tips': typeof AuthenticatedTipsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/operator/users': typeof AuthenticatedOperatorUsersRouteWithChildren
  '/_authenticated/operator/users/$userId': typeof AuthenticatedOperatorUsersUserIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/forecast'
    | '/onboarding'
    | '/settings'
    | '/tips'
    | '/transactions'
    | '/operator/users'
    | '/operator/users/$userId'
    | '/api/public/hooks/send-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/forecast'
    | '/onboarding'
    | '/settings'
    | '/tips'
    | '/transactions'
    | '/operator/users'
    | '/operator/users/$userId'
    | '/api/public/hooks/send-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/forecast'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/tips'
    | '/_authenticated/transactions'
    | '/_authenticated/operator/users'
    | '/_authenticated/operator/users/$userId'
    | '/api/public/hooks/send-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tips': {
      id: '/_authenticated/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof AuthenticatedTipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forecast': {
      id: '/_authenticated/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AuthenticatedForecastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator/users': {
      id: '/_authenticated/operator/users'
      path: '/operator/users'
      fullPath: '/operator/users'
      preLoaderRoute: typeof AuthenticatedOperatorUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operator/users/$userId': {
      id: '/_authenticated/operator/users/$userId'
      path: '/$userId'
      fullPath: '/operator/users/$userId'
      preLoaderRoute: typeof AuthenticatedOperatorUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedOperatorUsersRoute
    }
  }
}

interface AuthenticatedOperatorUsersRouteChildren {
  AuthenticatedOperatorUsersUserIdRoute: typeof AuthenticatedOperatorUsersUserIdRoute
}

const AuthenticatedOperatorUsersRouteChildren: AuthenticatedOperatorUsersRouteChildren =
  {
    AuthenticatedOperatorUsersUserIdRoute:
      AuthenticatedOperatorUsersUserIdRoute,
  }

const AuthenticatedOperatorUsersRouteWithChildren =
  AuthenticatedOperatorUsersRoute._addFileChildren(
    AuthenticatedOperatorUsersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedForecastRoute: typeof AuthenticatedForecastRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTipsRoute: typeof AuthenticatedTipsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedOperatorUsersRoute: typeof AuthenticatedOperatorUsersRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedForecastRoute: AuthenticatedForecastRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTipsRoute: AuthenticatedTipsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedOperatorUsersRoute: AuthenticatedOperatorUsersRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
